{{ range .cluster_node_instance_groups }}
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ $.cluster_name }}
  name: nodes
  <<: {{ .metadata | toJson }}
spec:
  cloudLabels:
    service: k8s_node
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/{{ $.cluster_name }}: ""
  role: Node
  kubernetesVersion: {{ $.k8s_version }}
  image: {{ $.cluster_image }}
  subnets:
  {{ range $.cluster_availability_zones }}
  - private-{{ . }}
  {{ end }}
  <<: {{ .spec | toJson }}
{{ end }}
