---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k8s-app: aws-iam-authenticator
  name: aws-iam-authenticator
  namespace: kube-system
data:
  config.yaml: |
    clusterID: {{ .cluster_name }}
    server:
        mapRoles:
        - roleARN: {{ .aws_iam_cluster_admin_role_arn }}
          username: kubernetes-admin
          groups:
          - system:masters
